CREATE DATABASE "MemberManagement"
    WITH 
    OWNER = root
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
 \c "MemberManagement"

 CREATE TABLE public.members
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    createdby character varying(100) COLLATE pg_catalog."default" NOT NULL,
    createddate timestamp without time zone NOT NULL,
    updatedby character varying(100) COLLATE pg_catalog."default",
    updateddate timestamp without time zone,
    CONSTRAINT "PK_members" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.members
    OWNER to root;


CREATE TABLE public.memberaccounts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    balance numeric NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    memberid bigint,
    createdby character varying(100) COLLATE pg_catalog."default" NOT NULL,
    createddate timestamp without time zone NOT NULL,
    updatedby character varying(100) COLLATE pg_catalog."default",
    updateddate timestamp without time zone,
    CONSTRAINT "PK_memberaccounts" PRIMARY KEY (id),
    CONSTRAINT "FK_memberaccounts_members_memberid" FOREIGN KEY (memberid)
        REFERENCES public.members (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public.memberaccounts
    OWNER to root;
-- Index: IX_memberaccounts_memberid

-- DROP INDEX public."IX_memberaccounts_memberid";

CREATE INDEX "IX_memberaccounts_memberid"
    ON public.memberaccounts USING btree
    (memberid ASC NULLS LAST)
    TABLESPACE pg_default;